name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: npm run build

      - name: deploy
        run: npm run deploy  